### ISSUE TITLE
Error: method not found:  SixLabors.Fonts.FontRectangle

### ISSUE THREAD

**Issue by WBorgo9** [Tagliatti/NetBarcode#46]
Hi 

I'm using the following code in VS 2019:
var barras = new Barcode( "12345678", NetBarcode.Type.EAN8);
var image = barras.GetImage();

or
var barras = new Barcode( "12345678", NetBarcode.Type.EAN8);
barras.SaveImageFile(@"C:\Users\test\Downloads\teste_barras.jpeg", ImageFormat.Jpeg);

I got this error:
System.MissingMethodException:
 'method not found: 
'SixLabors.Fonts.FontRectangle SixLabors.Fonts.TextMeasurer.Measure(System.String, SixLabors.Fonts.TextOptions)'.'

Can you help me, please?

Thanks

**Comment by Tagliatti** [comment]
Hello, what version of NetBarcode?

**Comment by WBorgo9** [comment]
Version: 1.7.2

**Comment by Tagliatti** [comment]
I don't use dotnet directly on Windows, so I can't tell you how to install the dependencies, but the errors are related to the lack of libc6-dev and libgdiplus.
Since version 1.5, the lib responsible for generating the image is ImageSharp. Maybe you can get more information on how to run it on Windows in the official repository https://github.com/SixLabors/ImageSharp
